spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/taco_cloud?currentSchema=taco_cloud
    username: postgres
  web:
    resources:
      static-locations: file:src/main/resources/static/
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: 'false'
